@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM 


"D:\Program Files\IAR Systems\Embedded Workbench Kickstart 6.0\common\bin\cspybat" "D:\Program Files\IAR Systems\Embedded Workbench Kickstart 6.0\rx\bin\rxproc.dll" "D:\Program Files\IAR Systems\Embedded Workbench Kickstart 6.0\rx\bin\rxemue20.dll"  %1 --plugin "D:\Program Files\IAR Systems\Embedded Workbench Kickstart 6.0\rx\bin\rxbat.dll" --backend -B "-p" "D:\Program Files\IAR Systems\Embedded Workbench Kickstart 6.0\rx\config\debugger\ior5f562n8.ddf" "--endian" "l" "--double" "32" "--core" "RX600" "--int" "32" "-d" "emue20" "--emu" "jlink" "--drv_communication" "USB" 


